<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru_RU">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="aboutdialog.ui" line="14"/>
        <source>About</source>
        <translation>О программе</translation>
    </message>
    <message>
        <location filename="aboutdialog.ui" line="33"/>
        <source>TextLabel</source>
        <translation></translation>
    </message>
    <message>
        <location filename="aboutdialog.cpp" line="32"/>
        <source>error while reading</source>
        <translation>ошибка при чтения файла</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="mainwindow.ui" line="20"/>
        <source>MainWindow</source>
        <translation>Главное окно</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="74"/>
        <source>&amp;Print</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="100"/>
        <source>&amp;Help</source>
        <translation>&amp;Помощь</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="113"/>
        <source>&amp;Close</source>
        <translation>&amp;Закрыть</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="132"/>
        <source>File</source>
        <translation>Файл</translation>
    </message>
    <message>
        <source>New</source>
        <translation type="vanished">Новый</translation>
    </message>
    <message>
        <source>Open</source>
        <translation type="vanished">Открыть</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="181"/>
        <source>Open (read only)</source>
        <translation>Открыть (только чтение)</translation>
    </message>
    <message>
        <source>Save</source>
        <translation type="vanished">Сохранить</translation>
    </message>
    <message>
        <source>Exit</source>
        <translation type="vanished">Выход</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="143"/>
        <source>Options</source>
        <translation>Параметры</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="153"/>
        <source>Themes</source>
        <translation>Темы</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="171"/>
        <source>&amp;New</source>
        <translation>&amp;Новый</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="176"/>
        <source>&amp;Open</source>
        <translation>&amp;Открыть</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="186"/>
        <source>&amp;Save</source>
        <translation>&amp;Сохранить</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="191"/>
        <source>&amp;Exit</source>
        <translation>&amp;Выход</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="196"/>
        <source>Help</source>
        <translation>Помощь</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="201"/>
        <source>English</source>
        <translation>Английский</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="206"/>
        <source>Russian</source>
        <translation>Русский</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="211"/>
        <source>Clientor</source>
        <translation>Clientor</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="216"/>
        <source>Dtor</source>
        <translation>Dtor</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="221"/>
        <source>Material-blue</source>
        <translation>Material-blue</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="226"/>
        <source>Material-dark</source>
        <translation>Material-dark</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="231"/>
        <source>NeonButtons</source>
        <translation>NeonButtons</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="236"/>
        <source>Ubuntu</source>
        <translation>Ubuntu</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="241"/>
        <source>Restore defaults</source>
        <translation>по умолчанию</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="vanished">Закрыть</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="83"/>
        <location filename="mainwindow.cpp" line="155"/>
        <location filename="mainwindow.cpp" line="180"/>
        <source>The current changes will be lost, continue?
</source>
        <translation>Текущие изменения будут потеряны, продолжить?\n</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="101"/>
        <location filename="mainwindow.cpp" line="111"/>
        <location filename="mainwindow.cpp" line="135"/>
        <source>Error</source>
        <translation>Ошибка</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="101"/>
        <source>Unable to open file for writing!</source>
        <translation>Не удается открыть файл для записи!</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="111"/>
        <source>Error writing file: %1</source>
        <translation>Ошибка при записи в файл: %1</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="128"/>
        <source>Open file</source>
        <translation>Открыть файл</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="128"/>
        <location filename="mainwindow.cpp" line="200"/>
        <source>Text files (*.txt);;All files (*.*)</source>
        <translation>Текстовые файлы (*.txt);;Все файлы (*.*)</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="135"/>
        <source>Unable to open file for reading!</source>
        <translation>Не удается открыть файл для чтения!</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="200"/>
        <source>Save file</source>
        <translation>Сохранение файла</translation>
    </message>
</context>
</TS>
