<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="aboutdialog.ui" line="14"/>
        <source>About</source>
        <translation>About</translation>
    </message>
    <message>
        <location filename="aboutdialog.ui" line="33"/>
        <source>TextLabel</source>
        <translation> </translation>
    </message>
    <message>
        <location filename="aboutdialog.cpp" line="32"/>
        <source>error while reading</source>
        <translation>error while reading</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="mainwindow.ui" line="20"/>
        <source>MainWindow</source>
        <translation>MainWindow</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="74"/>
        <source>&amp;Print</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="100"/>
        <source>&amp;Help</source>
        <translation>&amp;Help</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="113"/>
        <source>&amp;Close</source>
        <translation>&amp;Close</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="132"/>
        <source>File</source>
        <translation>File</translation>
    </message>
    <message>
        <source>New</source>
        <translation type="vanished">New</translation>
    </message>
    <message>
        <source>Open</source>
        <translation type="vanished">Open</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="181"/>
        <source>Open (read only)</source>
        <translation>Open (read only)</translation>
    </message>
    <message>
        <source>Save</source>
        <translation type="vanished">Save</translation>
    </message>
    <message>
        <source>Exit</source>
        <translation type="vanished">Exit</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="143"/>
        <source>Options</source>
        <translation>Options</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="153"/>
        <source>Themes</source>
        <translation>Themes</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="171"/>
        <source>&amp;New</source>
        <translation>&amp;New</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="176"/>
        <source>&amp;Open</source>
        <translation>&amp;Open</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="186"/>
        <source>&amp;Save</source>
        <translation>&amp;Save</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="191"/>
        <source>&amp;Exit</source>
        <translation>&amp;Exit</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="196"/>
        <source>Help</source>
        <translation>Help</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="201"/>
        <source>English</source>
        <translation>English</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="206"/>
        <source>Russian</source>
        <translation>Russian</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="211"/>
        <source>Clientor</source>
        <translation>Clientor</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="216"/>
        <source>Dtor</source>
        <translation>Dtor</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="221"/>
        <source>Material-blue</source>
        <translation>Material-blue</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="226"/>
        <source>Material-dark</source>
        <translation>Material-dark</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="231"/>
        <source>NeonButtons</source>
        <translation>NeonButtons</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="236"/>
        <source>Ubuntu</source>
        <translation>Ubuntu</translation>
    </message>
    <message>
        <location filename="mainwindow.ui" line="241"/>
        <source>Restore defaults</source>
        <translation>Restore defaults</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="vanished">Close</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="83"/>
        <location filename="mainwindow.cpp" line="155"/>
        <location filename="mainwindow.cpp" line="180"/>
        <source>The current changes will be lost, continue?
</source>
        <translation>The current changes will be lost, continue?\n</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="101"/>
        <location filename="mainwindow.cpp" line="111"/>
        <location filename="mainwindow.cpp" line="135"/>
        <source>Error</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="101"/>
        <source>Unable to open file for writing!</source>
        <translation>Unable to open file for writing!</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="111"/>
        <source>Error writing file: %1</source>
        <translation>Error writing file: %1</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="128"/>
        <source>Open file</source>
        <translation>Open file</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="128"/>
        <location filename="mainwindow.cpp" line="200"/>
        <source>Text files (*.txt);;All files (*.*)</source>
        <translation>Text files (*.txt);;All files (*.*)</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="135"/>
        <source>Unable to open file for reading!</source>
        <translation>Unable to open file for reading!</translation>
    </message>
    <message>
        <location filename="mainwindow.cpp" line="200"/>
        <source>Save file</source>
        <translation>Save file</translation>
    </message>
</context>
</TS>
